library(dplyr)

norfolk_lookup = tibble::tribble(
  ~district, ~town,
  "NR1",  "Norwich",
  "NR2",  "Norwich",
  "NR3",  "Norwich",
  "NR4",  "Norwich",
  "NR5",  "Norwich",
  "NR6",  "Norwich",
  "NR7",  "Norwich",
  "NR8",  "Norwich",
  "NR9",  "Norwich",
  "NR10", "Norwich",
  "NR11", "Norwich",
  "NR12", "Norwich",
  "NR13", "Norwich",
  "NR14", "Norwich",
  "NR15", "Norwich",
  "NR16", "Norwich",
  "NR17", "Attleborough",
  "NR18", "Wymondham",
  "NR19", "Dereham",
  "NR20", "Dereham",
  "NR21", "Fakenham",
  "NR22", "Walsingham",
  "NR23", "Wells-Next-The-Sea",
  "NR24", "Melton Constable",
  "NR25", "Holt",
  "NR26", "Sheringham",
  "NR27", "Cromer",
  "NR28", "North Walsham",
  "NR29", "Great Yarmouth",
  "NR30", "Great Yarmouth",
  "NR31", "Great Yarmouth",
  "NR32", "Lowestoft",
  "NR33", "Lowestoft",
  "NR34", "Beccles",
  "NR35", "Bungay",
  "NR46", "Norwich",
  "NR47", "Norwich",
  "NR50", "Norwich",
  "NR58", "Norwich",
  "NR59", "Norwich",
  "NR65", "Norwich",
  "NR66", "Norwich",
  "NR67", "Norwich",
  "NR70", "Norwich",
  "NR78", "Norwich",
  "NR79", "Norwich",
  "NR85", "Norwich",
  "NR86", "Norwich",
  "NR87", "Norwich",
  "NR93", "Norwich",
  "NR94", "Norwich",
  "NR95", "Norwich"
)

suffolk_lookup = tibble::tribble(
  ~district, ~town,
  "IP1",  "Ipswich",
  "IP2",  "Ipswich",
  "IP3",  "Ipswich",
  "IP4",  "Ipswich",
  "IP5",  "Ipswich",
  "IP6",  "Ipswich",
  "IP7",  "Ipswich",
  "IP8",  "Ipswich",
  "IP9",  "Ipswich",
  "IP10", "Ipswich",
  "IP11", "Felixstowe",
  "IP12", "Woodbridge",
  "IP13", "Woodbridge",
  "IP14", "Stowmarket",
  "IP15", "Aldeburgh",
  "IP16", "Leiston",
  "IP17", "Saxmundham",
  "IP18", "Southwold",
  "IP19", "Halesworth",
  "IP20", "Harleston",
  "IP21", "Diss",
  "IP22", "Diss",
  "IP23", "Eye",
  "IP24", "Thetford",
  "IP25", "Thetford",
  "IP26", "Thetford",
  "IP27", "Brandon",
  "IP28", "Bury St Edmunds",
  "IP29", "Bury St Edmunds",
  "IP30", "Bury St Edmunds",
  "IP31", "Bury St Edmunds",
  "IP32", "Bury St Edmunds",
  "IP33", "Bury St Edmunds",
  "IP38", "Ipswich",
  "IP39", "Ipswich",
  "IP41", "Ipswich",
  "IP42", "Ipswich",
  "IP43", "Ipswich",
  "IP44", "Ipswich",
  "IP45", "Ipswich",
  "IP51", "Ipswich",
  "IP52", "Ipswich",
  "IP53", "Ipswich",
  "IP60", "Ipswich",
  "IP68", "Ipswich",
  "IP69", "Ipswich",
  "IP75", "Ipswich",
  "IP76", "Ipswich",
  "IP77", "Ipswich",
  "IP83", "Ipswich",
  "IP84", "Ipswich",
  "IP91", "Ipswich",
  "IP92", "Ipswich"
)

border_lookup = tibble::tribble(
  ~district, ~town,
  "PE13", "Wisbech",
  "PE14", "Wisbech",
  "PE30", "King's Lynn",
  "PE31", "King's Lynn",
  "PE32", "King's Lynn",
  "PE33", "King's Lynn",
  "PE34", "King's Lynn",
  "PE36", "Hunstanton",
  "PE37", "Swaffham",
  "PE38", "Downham Market",
  "CB74", "Ely",
  "CB75", "Ely",
  "CB80", "Newmarket",
  "CB87", "Newmarket",
  "CB88", "Newmarket",
  "CB89", "Newmarket",
  "CB90", "Haverhill",
  "CB97", "Haverhill",
  "CB98", "Haverhill",
  "CB99", "Haverhill",
  "CO10", "Sudbury",
  "CO11", "Manningtree",
  "CO64", "Colchester",
  "CO65", "Colchester",
  "CO76", "Colchester",
  "CO85", "Bures"
)

postcode_town_lookup = bind_rows(norfolk_lookup, suffolk_lookup, border_lookup)

cat("\nPostcode district -> town lookup loaded.\n")
cat("  Norfolk (NR) districts mapped :", nrow(norfolk_lookup), "\n")
cat("  Suffolk (IP) districts mapped :", nrow(suffolk_lookup), "\n")
cat("  Border (PE/CB/CO) districts mapped :", nrow(border_lookup), "\n")
cat("  Total prefixes mapped :", nrow(postcode_town_lookup), "\n")